source 'https://rubygems.org'

# Declare your gem's dependencies in enroll_core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

gem 'acapi', git: "https://github.com/dchbx/acapi.git", branch: 'development'
gem 'money-rails', '~> 1.3.0'
gem "pundit", '~> 1.1.0'

# configuration support
gem "config", '~> 1.0.0'

gem 'devise', '~> 3.4.1'

gem 'rails-i18n', '4.0.8'

gem 'mongoid-versioning'
